const data = {
  products: [
    {
      _id: "1",
      name: "Diamond Pickaxe",
      category: "Pickaxe",
      image: "/images/minecraft_diamond_pickaxe.png",
      price: 2,
      brand: "Diamond",
      rating: 4,
      numReviews: 13,
      description:
        "High quality diamond pickaxe. Full durability. Unenchanted.",
      countInStock: 15,
    },
    {
      _id: "2",
      name: "Diamond Sword",
      category: "Sword",
      image: "/images/diamond_sword.png",
      price: 2,
      brand: "Diamond",
      rating: 4,
      numReviews: 24,
      description: "High quality diamond sword. Full durability. Unenchanted.",
      countInStock: 11,
    },
    {
      _id: "3",
      name: "Diamond Axe",
      category: "Axe",
      image: "/images/diamond_axe.png",
      price: 1,
      brand: "Diamond",
      rating: 4,
      numReviews: 10,
      description: "High quality diamond axe. Full durability. Unenchanted.",
      countInStock: 8,
    },
    {
      _id: "4",
      name: "Diamond Shovel",
      category: "Shovel",
      image: "/images/diamond_shovel.png",
      price: 0.5,
      brand: "Diamond",
      rating: 3,
      numReviews: 8,
      description: "High quality diamond shovel. Full durability. Unenchanted.",
      countInStock: 8,
    },
    {
      _id: "5",
      name: "Diamond Hoe",
      category: "Hoe",
      image: "/images/diamond_hoe.png",
      price: 0.5,
      brand: "Diamond",
      rating: 2,
      numReviews: 10,
      description: "High quality diamond hoe. Full durability. Unenchanted.",
      countInStock: 8,
    },
    {
      _id: "6",
      name: "Enchanted Diamond Pickaxe",
      category: "Pickaxe",
      image: "/images/enchanted_diamond_pickaxe.gif",
      price: 9,
      brand: "Diamond",
      rating: 5,
      numReviews: 20,
      description:
        "High quality enchanted diamond pickaxe. Full durability. Efficiency V, Unbreaking III, Fortune III.",
      countInStock: 3,
    },
    {
      _id: "7",
      name: "Enchanted Diamond Sword",
      category: "Sword",
      image: "/images/enchanted_diamond_sword.gif",
      price: 8,
      brand: "Diamond",
      rating: 5,
      numReviews: 7,
      description:
        "High quality enchanted diamond sword. Full durability. Sharpness V, Unbreaking III.",
      countInStock: 4,
    },
    {
      _id: "8",
      name: "Enchanted Diamond Axe",
      category: "Axe",
      image: "/images/enchanted_diamond_axe.gif",
      price: 7,
      brand: "Diamond",
      rating: 4.5,
      numReviews: 4,
      description:
        "High quality enchanted diamond axe. Full durability. Efficiency V, Unbreaking III.",
      countInStock: 8,
    },
    {
      _id: "9",
      name: "Enchanted Diamond Shovel",
      category: "Shovel",
      image: "/images/enchanted_diamond_shovel.gif",
      price: 4,
      brand: "Diamond",
      rating: 4.5,
      numReviews: 4,
      description:
        "High quality enchanted diamond shovel. Full durability. Efficiency V, Unbreaking III.",
      countInStock: 0,
    },
    {
      _id: "10",
      name: "Enchanted Diamond Hoe",
      category: "Hoe",
      image: "/images/enchanted_diamond_hoe.gif",
      price: 3,
      brand: "Diamond",
      rating: 3.5,
      numReviews: 4,
      description:
        "High quality enchanted diamond pickaxe. Full durability. Efficiency V, Unbreaking III.",
      countInStock: 0,
    },
  ],
};

export default data;
