const data = {
  products: [
    {
      _id: "1",
      name: "Diamond Axe",
      category: "Tools",
      image: "images/diamond_axe.png",
      price: 1,
      brand: "Diamond",
      rating: 5,
      numReviews: 10,
      description: "Full durability. No enchantments.",
    },
    {
      _id: "2",
      name: "Diamond Hoe",
      category: "Tools",
      image: "images/diamond_hoe.png",
      price: 0.5,
      brand: "Diamond",
      rating: 2,
      numReviews: 1,
      description: "Full durability. No enchantments.",
    },
    {
      _id: "3",
      name: "Diamond Pickaxe",
      category: "Tools",
      image: "images/minecraft_diamond_pickaxe.png",
      price: 1,
      brand: "Diamond",
      rating: 5,
      numReviews: 11,
      description: "Full durability. No enchantments.",
    },
    {
      _id: "4",
      name: "Diamond Sword",
      category: "Tools",
      image: "images/diamond_sword.png",
      price: 1,
      brand: "Diamond",
      rating: 5,
      numReviews: 10,
      description: "Full durability. No enchantments.",
    },
    {
      _id: "5",
      name: "Enchanted Diamond Axe",
      category: "Tools",
      image: "images/enchanted_diamond_axe.gif",
      price: 10,
      brand: "Diamond",
      rating: 5,
      numReviews: 10,
      description: "Full durability. Full enchantments.",
    },
    {
      _id: "6",
      name: "Enchanted Diamond Hoe",
      category: "Tools",
      image: "images/enchanted_diamond_hoe.gif",
      price: 4,
      brand: "Diamond",
      rating: 4,
      numReviews: 10,
      description: "Full durability. Full enchantments.",
    },
    {
      _id: "7",
      name: "Enchanted Diamond Pickaxe",
      category: "Tools",
      image: "images/enchanted_diamond_pickaxe.gif",
      price: 16,
      brand: "Diamond",
      rating: 5,
      numReviews: 10,
      description: "Full durability. Full enchantments.",
    },
    {
      _id: "8",
      name: "Enchanted Diamond Shovel",
      category: "Tools",
      image: "images/enchanted_diamond_shovel.gif",
      price: 10,
      brand: "Diamond",
      rating: 5,
      numReviews: 10,
      description: "Full durability. Full enchantments.",
    },
    {
      _id: "9",
      name: "Enchanted Diamond Sword",
      category: "Tools",
      image: "images/enchanted_diamond_sword.gif",
      price: 15,
      brand: "Diamond",
      rating: 5,
      numReviews: 10,
      description: "Full durability. Full enchantments.",
    },
  ],
};

export default data;
